version: '3'

services:
  notifier:
    build: .
    image: github-release-notifier:1
    container_name: github-release-notifier
    volumes:
    - ./conf.ini:/app/conf.ini

  mailhog:
    image: mailhog/mailhog:v1.0.1
    ports:
      - "8025:8025"
      - "1025:1025"

  ofelia:
    image: mcuadros/ofelia:latest
    depends_on:
      - notifier
    command: daemon --config=/opt/config.ini
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./ofelia.ini:/opt/config.ini
